# Polymorphic build - varies binary hash/size per build (timestamp-based seed)
function(add_polymorphic_stub target)
    string(TIMESTAMP BUILD_SEED "%Y%m%d%H%M%S" UTC)
    set(PAD_SIZE 512)
    set(PAD_DATA "")
    foreach(i RANGE 1 ${PAD_SIZE})
        math(EXPR r "(${i} * 1103515245 + ${BUILD_SEED} + 12345) & 0x7FFFFFFF")
        math(EXPR b "${r} % 256")
        if(PAD_DATA STREQUAL "")
            set(PAD_DATA "${b}")
        else()
            set(PAD_DATA "${PAD_DATA}, ${b}")
        endif()
    endforeach()
    
    set(JUNK_FILE "${CMAKE_CURRENT_BINARY_DIR}/poly_junk.cpp")
    configure_file("${CMAKE_SOURCE_DIR}/polymorphic/junk_stub.cpp.in" "${JUNK_FILE}" @ONLY)
    target_sources(${target} PRIVATE "${JUNK_FILE}")
endfunction()
